name: Smart contracts build

on: [push, workflow_dispatch]

env:
  LAB2_DIR: "./Lab2_tokens"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile, test and analyze ${{ env.LAB2_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        working-directory: ${{ env.LAB2_DIR }}

      - name: Setup node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
        working-directory: ${{ env.LAB2_DIR }}

      - name: Install npm deps
        run: npm install
        working-directory: ${{ env.LAB2_DIR }}

      - name: Hardhat check
        run: npx hardhat check
        working-directory: ${{ env.LAB2_DIR }}

      - name: Compile
        run: npx hardhat compile
        working-directory: ${{ env.LAB2_DIR }}

      - name: Tests
        run: npx hardhat test
        working-directory: ${{ env.LAB2_DIR }}